version: '3.3'

services:
  nuxt:
    build:
      context: .
    image: nuxt_dev
    container_name: nuxt_dev
    command: npm run dev
    volumes:
    - .:/app
    - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - "json-server"

  json-server:
    image: vimagick/json-server
    command: -H 0.0.0.0 -p 4000 -w db.json
    ports:
      - "4000:4000"
    volumes:
      # - ./data:/data
      - ./:/data
    restart: always 
